VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsMoreDFLocationInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'a simple class for getting data field locations in the data processing system.

Public TargetShName As String
Public ColNum As Integer
Public StartRowNum As Integer
Public EndRowNum As Integer


